#!/usr/bin/env python3

# Main module, either calls the interpreter or executes a file.

from os.path import isfile as is_file
from sys import argv

from ezcript_lang.tokens import Token, TokenType
from ezcript_lang.lexer import Lexer
from ezcript_lang.repl import repl


def main() -> None:
    args = argv[1:]

    if not args:  # Args is empty
        print("""
Welcome to Ezcript v0.0.1!
Type "help()" for more information""")
        repl()
    else:
        for arg in args:
            if arg in {'--help', '-h'}:
                print("Here's some help about the interpreter")
                # Help code goes here
                break

            elif is_file(arg):
                print(f"Executing {arg}...")  # DEBUG

                # ORIGINAL CODE
                with open(arg, "r") as file:
                    lines = file.readlines()

                for line in lines:
                    lexer: Lexer = Lexer(line)
                    while (token := lexer.next_token()) != Token(TokenType.EOF,
                                                                 ''):
                        print(token)
            else:
                print(f'The file "{arg}" does not exist.')


if __name__ == '__main__':
    main()
