#!/usr/bin/env python3

import os
import sys

from ezcript_lang.repl import repl
from ezcript_lang.tokens import (
    Token,
    TokenType,
)
from ezcript_lang.lexer import Lexer

args = sys.argv
args.pop(0)


def main() -> None:
    if len(args) == 0:
        print("Welcome to Ezcript v0.0.1!")
        print("Write \"help()\" for more information")

        repl()
    else:
        for arg in args:
            if not os.path.isfile(
                    arg) and arg[0:2] != '--' and arg[0:1] != '-':
                print("El archivo no existe")
            elif arg[-3:] != '.ez' and arg[0:2] != '--' and arg[0:1] != '-':
                print("Ese no es un archivo soportado por el lenguaje!")
            elif arg in ('--help', '-h'):
                print("Aquí hay un poco de ayuda acerca del interprete")
            elif os.path.isfile(arg) and arg[-3:] == '.ez':
                with open(arg, "r") as file:
                    lines = file.readlines()

                for line in lines:
                    lexer: Lexer = Lexer(line)
                    while (token := lexer.next_token()) != Token(
                            TokenType.EOF, ''):
                        print(token)


if __name__ == '__main__':
    main()
